on: [push]

jobs:
#   test:
#     runs-on: ubuntu-latest
#     container:
#       image: ghcr.io/jsouter/alpine:latest
#       credentials:
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: say hello
#         run: echo hello
  sardana:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jsouter/ophyd-v2-tango/sardemo:v3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      - name: start sardana
        run: |
          /startsard.sh
          sleep 10
          python3 exampledevice.py &
          python3 -m unittest test_with_dev_proxy.py
          python3 -m unittest test_with_mock_proxy.py


