on: [push]

jobs:
#   test:
#     runs-on: ubuntu-latest
#     container:
#       image: ghcr.io/jsouter/alpine:latest
#       credentials:
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: say hello
#         run: echo hello
  sardana:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jsouter/ophyd-v2-tango/sardemo:v4
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      # - name: pipenv install
      #   run: |
      #     python3 -m pip install --upgrade pipenv wheel
      #     pipenv install . 
      #     pipenv shell
      - name: pip install
        run: |
          pip install . 
      - name: mock proxy unit tests
        run: |
          python3 -m unittest tests/test_with_mock_proxy.py
      - name: start tango, run example device tests
        run: |
          service mariadb start
          /usr/local/tango/bin/tango start
          python3 exampledevice.py &
          sleep 10
          python3 -m unittest tests/test_example_device.py
      - name: start sardana and run tests
        run: |
          yes y | Sardana demo &
          sleep 10
          python3 -m unittest tests/test_sardana_motor.py
      - name: linting
        # continue-on-error: true
        run: |
          python3 -m flake8 src/ophyd_tango_devices/*
          python3 -m mypy src/ophyd_tango_devicesotd/*

