on: [push]

jobs:
  run-tests-and-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jsouter/ophyd-v2-tango/sardemo:v4
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      - name: pip install
        run: |
          pip install . 
      - name: sim proxy unit tests
        run: |
          python3 -m unittest tests/test_sim_proxy.py
      - name: start tango, run example device tests
        run: |
          service mariadb start
          /usr/local/tango/bin/tango start
          python3 exampledevice.py &
          sleep 10
          python3 -m unittest tests/test_example_device.py
      - name: start sardana and run tests
        run: |
          yes y | Sardana demo &
          sleep 10
          python3 -m unittest tests/test_sardana_motor.py
      - name: linting
        run: |
          python3 -m flake8 ophyd_tango_devices
          pip install mypy
          python3 -m mypy ophyd_tango_devices

